BEGIN;

DELETE FROM
    odl."t_{{params.source}}_{{params.entity}}"
WHERE
    _logical_date = '{{logical_date.strftime("%Y-%m-%d")}}'
    AND account_slug = '{{params.account_slug}}';

INSERT INTO
    odl."t_{{params.source}}_{{params.entity}}" (
        account_slug,
        watch_id,
        pageview_id,
        counter_id,
        client_id,
        counter_user_id_hash,
        hit_date,
        hit_datetime,
        title,
        page_charset,
        goals_id,
        hit_url,
        referer,
        utm_campaign,
        utm_content,
        utm_medium,
        utm_source,
        utm_term,
        openstat_ad,
        openstat_campaign,
        openstat_service,
        openstat_source,
        operating_system,
        label_from,
        has_gclid,
        gclid,
        last_traffic_source,
        last_search_engine_root,
        last_search_engine,
        last_adv_engine,
        last_social_network,
        last_social_network_profile,
        recommendation_system,
        messenger,
        browser,
        browser_major_version,
        browser_minor_version,
        browser_country,
        browser_engine,
        browser_engine_version_1,
        browser_engine_version_2,
        browser_engine_version_3,
        browser_engine_version_4,
        browser_language,
        client_timezone,
        cookie_enabled,
        device_category,
        javascript_enabled,
        mobilePhone,
        mobile_phone_model,
        operating_system_root,
        physical_screen_height,
        physical_screen_width,
        screenColors,
        screen_format,
        screen_height,
        screen_orientation,
        screen_orientation_name,
        screen_width,
        window_client_height,
        window_client_width,
        ip_address,
        region_city,
        region_country,
        region_city_id,
        region_country_id,
        is_pageview,
        is_turbo_page,
        is_turbo_app,
        is_iframe,
        is_link,
        is_download,
        is_not_bounce,
        is_artificial,
        ecommerce,
        params,
        parsed_params_key_1,
        parsed_params_key_2,
        parsed_params_key_3,
        parsed_params_key_4,
        parsed_params_key_5,
        parsed_params_key_6,
        parsed_params_key_7,
        parsed_params_key_8,
        parsed_params_key_9,
        parsed_params_key_10,
        http_error,
        network_type,
        share_service,
        share_url,
        share_title,
        _start_date,
        _logical_date
    )
SELECT
    '{{params.account_slug}}' AS account_slug,
    "watch_id" :: numeric(20),
    "pageview_id" :: int4,
    "counter_id" :: int4,
    "client_id" :: numeric(20),
    "counter_user_id_hash" :: numeric(20),
    "hit_date" :: date,
    "hit_datetime" :: timestamp,
    "title" :: text,
    "page_charset" :: text,
    "goals_id" :: jsonb,
    "hit_url" :: text,
    "referer" :: text,
    "utm_campaign" :: text,
    "utm_content" :: text,
    "utm_medium" :: text,
    "utm_source" :: text,
    "utm_term" :: text,
    "openstat_ad" :: text,
    "openstat_campaign" :: text,
    "openstat_service" :: text,
    "openstat_source" :: text,
    "operating_system" :: text,
    "label_from" :: text,
    "has_gclid" :: int2,
    "gclid" :: text,
    "last_traffic_source" :: text,
    "last_search_engine_root" :: text,
    "last_search_engine" :: text,
    "last_adv_engine" :: text,
    "last_social_network" :: text,
    "last_social_network_profile" :: text,
    "recommendation_system" :: text,
    "messenger" :: text,
    "browser" :: text,
    "browser_major_version" :: int4,
    "browser_minor_version" :: int4,
    "browser_country" :: text,
    "browser_engine" :: text,
    "browser_engine_version_1" :: int4,
    "browser_engine_version_2" :: int4,
    "browser_engine_version_3" :: int4,
    "browser_engine_version_4" :: int4,
    "browser_language" :: text,
    "client_timezone" :: int2,
    "cookie_enabled" :: int2,
    "device_category" :: varchar(16),
    "javascript_enabled" :: int2,
    "mobilePhone" :: text,
    "mobile_phone_model" :: text,
    "operating_system_root" :: text,
    "physical_screen_height" :: int4,
    "physical_screen_width" :: int4,
    "screenColors" :: int2,
    "screen_format" :: text,
    "screen_height" :: int4,
    "screen_orientation" :: int2,
    "screen_orientation_name" :: text,
    "screen_width" :: int4,
    "window_client_height" :: int4,
    "window_client_width" :: int4,
    "ip_address" :: text,
    "region_city" :: text,
    "region_country" :: text,
    "region_city_id" :: int8,
    "region_country_id" :: int8,
    "is_pageview" :: int2,
    "is_turbo_page" :: int2,
    "is_turbo_app" :: int2,
    "is_iframe" :: int2,
    "is_link" :: int2,
    "is_download" :: int2,
    "is_not_bounce" :: int2,
    "is_artificial" :: int2,
    "ecommerce" :: text,
    "params" :: text,
    "parsed_params_key_1" :: jsonb,
    "parsed_params_key_2" :: jsonb,
    "parsed_params_key_3" :: jsonb,
    "parsed_params_key_4" :: jsonb,
    "parsed_params_key_5" :: jsonb,
    "parsed_params_key_6" :: jsonb,
    "parsed_params_key_7" :: jsonb,
    "parsed_params_key_8" :: jsonb,
    "parsed_params_key_9" :: jsonb,
    "parsed_params_key_10" :: jsonb,
    "http_error" :: text,
    "network_type" :: text,
    "share_service" :: text,
    "share_url" :: text,
    "share_title" :: text,
    '{{ti.start_date.strftime("%Y/%m/%d %H:%M:%S")}}' :: timestamp AS _start_date,
    '{{logical_date.strftime("%Y-%m-%d")}}' AS _logical_date
FROM
    stg."{{params.buffer_table_pref}}_{{ts_nodash}}";

COMMIT;