schema = [
    {"name": "name", "type": "text"},
    {"name": "email", "type": "text"},
    {"name": "phone", "type": "text"},
    {"name": "city", "type": "text"},
    {"name": "university", "type": "text"},
    {"name": "input", "type": "text"},
    {"name": "referer", "type": "text"},
    {"name": "form_id", "type": "text"},
    {"name": "sent", "type": "text"},
    {"name": "request_id", "type": "text"},
    {"name": "utm_source", "type": "text"},
    {"name": "utm_medium", "type": "text"},
    {"name": "utm_campaign", "type": "text"},
    {"name": "utm_id", "type": "text"},
    {"name": "utm_content", "type": "text"},
    {"name": "_start_date", "type": "timestam"},
    {"name": "_logical_date", "type": "char(10)"},
]
